---
apiVersion: v1
kind: Namespace
metadata:
  name: codeserver
  labels:
    app: cs
---
apiVersion: v1 
kind: Secret 
metadata:
  name: cs-secret 
  namespace: codeserver
data:
  # password
  PASSWORD: Y2hhbmdlaXQ=
  SUDO_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: cs-cm 
  namespace: codeserver
  labels:
    app: cs
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
# k get svc -A to see external IP of ingress controller
  PROXY_DOMAIN: code-146.190.5.177.nip.io
