---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-deploy
  namespace: codeserver
  labels:
    app: cs
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: cs
      type: pod
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      name: cs-pod
      # namespace: codeserver -> assumed to be in same namespace as deployment
      labels:
        app: cs
        type: pod
    spec:
    # volume is deployment level
      volumes: 
      - name: src-vol
        persistentVolumeClaim:
          claimName: cs-pvc
    # volumeMount is container level
      containers:
      - name: cs-container 
        image: linuxserver/code-server:amd64-4.95.3
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: cs-cm
        - secretRef:
            name: cs-secret
        ports:
        - containerPort: 8443
        resources:
          requests: 
            memory: 512M
            cpu: 200m # 1/5 of a CPU
          limits: 
            memory: 512M
            cpu: 200m # 1/5 of a CPU
        volumeMounts: 
        - name: src-vol
          mountPath: /config/workspace
---
apiVersion: v1
kind: Service
metadata:
  name: cs-svc
  namespace: codeserver
  labels:
    app: cs
spec: 
  type: ClusterIP
  selector:
    app: cs
    type: pod
  ports: 
    - name: csport
      port: 8443
      targetPort: 8443
