---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
  labels:
    app: minio
data:
  # password
  MINIO_ROOT_PASSWORD: YWRtaW5hZG1pbg==
# git ignore secret, so good to separate

