apiVersion: v1
kind: Pod
metadata:
  name: dov-pod
  namespace: myns
  labels:
    app: dov
spec:
  containers:
  - name: dov-container 
    image: chukmunnlee/dov-bear:v5
    imagePullPolicy: IfNotPresent
#    env:
#    - name: INSTANCE_NAME
#      value: "my dov bear"
#    - name: INSTANCE_HASH
#      valueFrom: 
#        fieldRef:
#          fieldPath: status.podIP
    ports:
      - containerPort: 3000
        protocol: TCP

# if never pull, images must be pre-loaded on nodes
# matching of image relies on tag, but some people may have override it
# thus, good practice not to reuse tags
# can use manifest digest (on dockerhub) as well for image chukmunnlee/dov-bear:v5@sha256:XXXXXX
# volume from - can refer to runtime envs
