---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
data:
  # password
  MINIO_ROOT_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio-ns
  labels:
    app: minio-cm
data:
  MINIO_ROOT_USER: minioadmin
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: node1,node2,node3,node4
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"
