apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio-ns
spec:
  clusterIP: None
  ports:
    - port: 9090
      name: console-port
    - port: 9000
      name: server-port
  selector:
    app: minio
