---
apiVersion: v1
kind: Namespace
metadata:
  name: dovns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  namespace: dovns
  labels:
    app: dov 
    name: dov-cm
data:
  INSTANCE_NAME: dov-bear

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: dovns
  labels:
    app: dov
    name: dov-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dov
      name: dov-po
  template:
    metadata:
      labels:
        app: dov
        name: dov-po
    spec:
      containers:
      - name: dov-container
        image: chukmunnlee/dov-bear:v4
        env:
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']
        envFrom:
        - configMapRef:
            name: dov-cm
        ports:
        - containerPort: 3000
        resources: 
          requests: 
            cpu: 100m
            memory: 128Mi
          limits: 
            cpu: 100m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: dovns
  labels:
    app: dov
    name: dov-svc
spec:
  type: ClusterIP
  selector:
    app: dov
    name: dov-po
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dov-hpa
  namespace: dovns
  labels:
    app: dov
spec: 
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1 # Deployment
    kind: Deployment
    name: dov-deploy
  metrics: 
  - type: Resource # only resource for metrics server
    resource: 
      name: cpu # only memory/CPU here for metrics server
      target: 
        type: Utilization
        averageUtilization: 20
  - type: Resource
    resource: 
      name: memory
      target:
        type: Utilization
        averageUtilization: 20
