apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"env":"dev"},"name":"dev-ns"}}
    labels:
      env: dev
    name: dev-ns
- apiVersion: v1
  data:
    INSTANCE_NAME: dov-bear
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"INSTANCE_NAME":"dov-bear"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"dov","env":"dev","name":"dov-cm"},"name":"dev-dov-cm","namespace":"dev-ns"}}
    labels:
      app: dov
      env: dev
      name: dov-cm
    name: dev-dov-cm
    namespace: dev-ns
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"dov","env":"dev","name":"dov-svc"},"name":"dev-dov-svc","namespace":"dev-ns"},"spec":{"ports":[{"port":3000,"targetPort":3000}],"selector":{"app":"dov","env":"dev","name":"dov-po"},"type":"ClusterIP"}}
    labels:
      app: dov
      env: dev
      name: dov-svc
    name: dev-dov-svc
    namespace: dev-ns
  spec:
    ports:
    - port: 3000
      targetPort: 3000
    selector:
      app: dov
      env: dev
      name: dov-po
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"dov","env":"dev","name":"dov-deploy"},"name":"dev-dov-deploy","namespace":"dev-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"dov","env":"dev","name":"dov-po"}},"template":{"metadata":{"labels":{"app":"dov","env":"dev","name":"dov-po"}},"spec":{"containers":[{"env":[{"name":"INSTANCE_HASH","valueFrom":{"fieldRef":{"fieldPath":"metadata.labels['pod-template-hash']"}}}],"envFrom":[{"configMapRef":{"name":"dev-dov-cm"}}],"image":"chukmunnlee/dov-bear:v5","name":"dov-container","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"100m","memory":"128Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
    labels:
      app: dov
      env: dev
      name: dov-deploy
    name: dev-dov-deploy
    namespace: dev-ns
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: dov
        env: dev
        name: dov-po
    template:
      metadata:
        labels:
          app: dov
          env: dev
          name: dov-po
      spec:
        containers:
        - env:
          - name: INSTANCE_HASH
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['pod-template-hash']
          envFrom:
          - configMapRef:
              name: dev-dov-cm
          image: chukmunnlee/dov-bear:v5
          name: dov-container
          ports:
          - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"dov","env":"dev"},"name":"dev-dov-hpa","namespace":"dev-ns"},"spec":{"maxReplicas":4,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":20,"type":"Utilization"}},"type":"Resource"},{"resource":{"name":"memory","target":{"averageUtilization":20,"type":"Utilization"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"dev-dov-deploy"}}}
    labels:
      app: dov
      env: dev
    name: dev-dov-hpa
    namespace: dev-ns
  spec:
    maxReplicas: 4
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 20
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: 20
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: dev-dov-deploy
kind: List
metadata: {}
